kind: Service
apiVersion: v1
metadata:
  name: neo4j
spec:
  selector:
    app: neo4j
  ports:
    - protocol: TCP
      port: 7474
      targetPort: 7474
      name: http
    - protocol: TCP
      port: 7687
      targetPort: 7687
      name: bolt
    - protocol: TCP
      port: 7473
      targetPort: 7473
      name: curl
  type: ClusterIP
